name: science
dependencies:
  # main scientific packages
  - defaults::python=3.6.6
  - defaults::mkl=2018.0.3
  - defaults::scipy=1.1.0
  - defaults::numpy=1.14.5

  - conda-forge::kwant=1.3.2
  - conda-forge::sympy=1.1.1

  # data analysis and serialisation
  - conda-forge::holoviews=1.10.6
  - conda-forge::xarray=0.10.7
  - conda-forge::pandas=0.23.1
  - conda-forge::deepdish=0.3.4

  # parallel computation
  - defaults::ipyparallel=6.2.2
  - conda-forge::hpc05=v1.24

  # kwant build depenendencies (required for kwant environment)
  - conda-forge::mumps=5.0.2
  - conda-forge::lapack=3.6.1
  - conda-forge::cython=0.28.3
