name: kwant-dev
dependencies:
  - defaults::python=3.6.5
  - defaults::mkl=2018.0.2
  - defaults::scipy=1.0.1
  - defaults::numpy=1.14.2
  - defaults::sympy=1.1.1
  - defaults::xarray=0.10.2

  - conda-forge::holoviews=1.9.5
  - conda-forge::deepdish=0.3.4

  - defaults::ipyparallel=6.1.1
  - conda-forge::hpc05=v1.24

  - defaults::gcc=4.8.5
  - conda-forge::mumps=5.0.2
  - conda-forge::lapack=3.6.1
  - conda-forge::cython=0.28.1
  - conda-forge::pytest=3.5.0
