name: science
dependencies:
  - conda-forge::python=3.6.6

  # misc tools
  - conda-forge::nbdime=1.0.2

  # main scientific packages
  - conda-forge::scipy=1.1.0
  - conda-forge::numpy=1.15.1

  - conda-forge::kwant=1.3.3
  - conda-forge::sympy=1.2.0
  - conda-forge::adaptive=0.5.0

  # data analysis, visulation and serialisation
  - conda-forge::matplotlib=2.2.3
  - conda-forge::plotly=3.1.1
  - conda-forge::holoviews=1.10.7
  - conda-forge::xarray=0.10.8
  - conda-forge::pandas=0.23.4
  - conda-forge::deepdish=0.3.4

  # parallel computation
  - conda-forge::ipyparallel=6.2.2
  - conda-forge::hpc05=v1.26

  # kwant build depenendencies (required for kwant environment)
  - conda-forge::mumps=5.0.2
  - conda-forge::lapack=3.6.1
  - conda-forge::cython=0.28.4
  - conda-forge::gcc=4.8.5

  # various packages that handle codes installed from sources
  - conda-forge::pytest=3.7.4
  - conda-forge::pytest-cov=2.5.1
  - conda-forge::pytest-flakes=4.0.0
  - conda-forge::line_profiler=2.1.2

  # scikit packages
  - conda-forge::scikit-learn=0.19.2
  - conda-forge::scikit-image=0.14.0

  # machine-learning packages
  - conda-forge::keras=2.2.2
  - conda-forge::tensorflow=1.10.0

  # semicon
  - pip:
    - git+https://gitlab.kwant-project.org/semicon/semicon.git@v0.1.0
