name: science
dependencies:
  # - conda-forge::python=3.7.1

  # misc tools
  - conda-forge::nbdime=1.0.6

  # main scientific packages
  - conda-forge::scipy=1.3.0
  - conda-forge::numpy=1.16.4
  - conda-forge::adaptive=0.8.1

  # data analysis, visulation and serialisation
  - conda-forge::matplotlib=3.1.1
  - conda-forge::plotly=3.10.0
  - conda-forge::holoviews=1.12.3
  - conda-forge::xarray=0.12.2
  - conda-forge::pandas=0.24.2
  - conda-forge::deepdish=0.3.4

  # various packages that handle codes installed from sources
  - conda-forge::pytest=5.0.0
  - conda-forge::pytest-cov=2.7.1
  - conda-forge::pytest-flakes=4.0.0
  - conda-forge::line_profiler=2.1.2

  # scikit packages
  - conda-forge::scikit-learn=0.21.2
  - conda-forge::scikit-image=0.15.0

  # machine-learning packages
  - conda-forge::keras=2.2.4
  - conda-forge::tensorflow=1.13.1
