name: science
dependencies:
  # main scientific packages
  - defaults::mkl=2018.0.3
  - defaults::scipy=1.1.0
  - defaults::numpy=1.14.5

  - conda-forge::kwant=1.3.2
  - conda-forge::sympy=1.1.1

  # data analysis and serialisation
  - conda-forge::holoviews=1.10.7
  - conda-forge::xarray=0.10.7
  - conda-forge::pandas=0.23.3
  - conda-forge::deepdish=0.3.4

  # parallel computation
  - defaults::ipyparallel=6.2.2
  - conda-forge::hpc05=v1.24

  # kwant build depenendencies (required for kwant environment)
  - conda-forge::mumps=5.0.2
  - conda-forge::lapack=3.6.1
  - conda-forge::cython=0.28.3

  # various packages that handle codes installed from sources
  - conda-forge::pytest=3.6.2
  - conda-forge::pytest-cov=2.5.1
  - conda-forge::pytest-flakes=2.0.0

  # semicon
  - pip:
    - git+https://gitlab.kwant-project.org/semicon/semicon.git@v0.1.0
